### ISSUE TITLE
Colocar mais robôs nos níveis seguintes

### ISSUE THREAD

**Issue by tonyfrance** [pontesupe/robots#1]
Mateus, o programa ja esta quase feito, nao estou sabendo colocar mais robos nos outros niveis.

**Comment by pontesupe** [comment]
Ok Antonio, estou dando uma olhada no programa aqui. 
Vamos ver se conseguimos colocar.

**Comment by drbeco** [comment]
Pode editar esse título para : "Colocar mais robôs nos níveis seguintes"

Obrigado.

**Comment by tonyfrance** [comment]
pronto ta feito.
