### ISSUE TITLE
Passei de fase e morri

### ISSUE THREAD

**Issue by drbeco** [pontesupe/robots#2]
Bug: quando eu venci o nível 1 ele me deu os parabéns e disse:

```
Parabéns você passou de fase!
        Tecle p para próxima fase.
p
```

E então não deu tempo de eu jogar e já apareceu a mensagem dizendo que morri.

**Comment by tonyfrance** [comment]
quando voce passa de fase , tecla p para ir para proxima fase, o humano o lixo e o robo sao gerados aleatoriamente.
vou consertar esse bug de nao poder aparecer nas mesmas casas

**Comment by tonyfrance** [comment]
conserto feito
