### ISSUE TITLE
atualizaçao

### ISSUE THREAD

**Issue by tonyfrance** [pontesupe/robots#4]
professor gostaria de saber se posso atualizar o programa, por estética.
se possível caso isso prejudique a nota não farei a atualização.

**Comment by tonyfrance** [comment]
professor essa mudança de estetica e necessaria ,la esta gerando um bug, que quando os robos se chocassem vc passaria de fase e ate trocaria de desenho por os " . "(pontos) virariao " @ " .

**Comment by tonyfrance** [comment]
alteração feita, bugs resolvidos, estética  restaurada.

**Comment by pontesupe** [comment]
Concordo com a correção,
Agora o programa está completo :)
